joint_limits:
  joint_1:
    max_effort: 56.0
    max_position: !degrees 130.0
    max_velocity: !degrees 360.0
    min_position: !degrees -130.0
  joint_2:
    max_effort: 56.0
    max_position: !degrees 130.0
    max_velocity: !degrees 288.0
    min_position: !degrees -130.0
  joint_3:
    max_effort: 56.0
    max_position: 0.0
    max_velocity: 0.2
    min_position: -0.2
  joint_4:
    max_effort: 8.4
    max_position: !degrees 360.0
    max_velocity: !degrees 360.0
    min_position: !degrees -360.0
  joint_5:
    max_effort: 0.0
    max_position: !degrees 0.0
    max_velocity: !degrees 0.0
    min_position: !degrees 0.0
  joint_6:
    max_effort: 0.0
    max_position: !degrees 0.0
    max_velocity: !degrees 0.0
    min_position: !degrees 0.0
