# Configuration file for HIWIN D2COE drive
vendor_id: 0x0000aaaa
product_id: 0x00000003
assign_activate: 0x0300  # DC Synch register
auto_fault_reset: true  # true = automatic fault reset, false = fault reset on rising edge command interface "reset_fault"
auto_state_transitions: true

sm:  # Sync Manager
  - {index: 2, type: output, pdo: rpdo, watchdog: enable}
  - {index: 3, type: input, pdo: tpdo, watchdog: disable}

sdo:  # sdo data to be transferred at drive startup
  - {index: 0x1C32, sub_index: 1, type: uint16, value: 2} # Set Sync mode to DC-Mode - Synchron with SYNC0 Event
  - {index: 0x1C33, sub_index: 1, type: uint16, value: 2} # Set Sync mode to DC-Mode - Synchron with SYNC0 Event

tpdo:  # TxPDO = transmit PDO Mapping
  - index: 0x1a00
    channels:
      - {index: 0x603f, sub_index: 0, type: uint16}  # Error code
      - {index: 0x6041, sub_index: 0, type: uint16}  # Status word
      - {index: 0x6061, sub_index: 0, type: int8}  # Mode of operation display
      - {index: 0x6064, sub_index: 0, type: int32, state_interface: position, factor: 5.9921124526782860535862796464529e-7}  # Position actual value 2Ï€ / (131072 * 80)
      - {index: 0x60f4, sub_index: 0, type: int32}  # Following error actual value
      - {index: 0x60fd, sub_index: 0, type: uint32}  # Digital inputs

rpdo:  # RxPDO = receive PDO Mapping
  - index: 0x1600
    channels:
      - {index: 0x6040, sub_index: 0, type: uint16, default: 0}  # Control word
      - {index: 0x6060, sub_index: 0, type: int8, default: 8}  # Mode of operation
      - {index: 0x607a, sub_index: 0, type: int32, command_interface: position, default: .nan, factor: 1668860.536075272435991930610621}  # Target position
      - {index: 0x60fe, sub_index: 1, type: uint32, default: 0}  # Digital Output Functionalities
